### ISSUE TITLE
Exit with non-zero on failed html build

### ISSUE THREAD

**Issue by coyotte508** [huggingface/doc-builder#104]
I'm not sure if this is a problem with `doc-builder` or the github action, but in this run: https://github.com/huggingface/transformers/runs/5309174496?check_suite_focus=true

```bash
Building HTML files. This will take a while :-)
Traceback (most recent call last):
  File "/home/runner/.local/bin/doc-builder", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.8/site-packages/doc_builder/commands/doc_builder_cli.py", line 39, in main
    args.func(args)
  File "/home/runner/.local/lib/python3.8/site-packages/doc_builder/commands/build.py", line 145, in build_command
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 134.
```

And yet the rest of the steps executed and the CI was green

**Comment by coyotte508** [comment]
The issue is in the CI - in the `run` command, `&&` should be used
