### ISSUE TITLE
preview taking a lot of time

### ISSUE THREAD

**Issue by jegork** [huggingface/doc-builder#331]
Hello!

I have trouble running the preview command.
First, I run the build command:
```sh
doc-builder build transformers docs/source/en/ --build_dir ~/tmp/test-build
```

Afterwards, I run:
```sh
doc-builder preview transformers ~/tmp/test-build
```

Which leads me to the following prompt:
```sh
Building the MDX files:  31%|█████████████████████████████████████████████▌                                                                                                       | 79/258 [01:53<19:06,  6.40s/it]
```

And this process would take infinitely long, it didn't even finish after 8 hours. I am not sure whether this is expected or some bug.

NB: it gets stuck at around 77/258, before this everything is super fast.

I am running M1 Mac OS.

Thanks!

**Comment by mariosasko** [comment]
Hi! What do you get when you interrupt the process (CTRL + C) while it's hanging?

**Comment by jegork** [comment]
Hey @mariosasko 

I have tried stopping it at 74/269 and 81/269 and in both cases got the following trace.

```shell
Traceback (most recent call last):
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/bin/doc-builder", line 8, in <module>
    sys.exit(main())
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/lib/python3.9/site-packages/doc_builder/commands/doc_builder_cli.py", line 47, in main
    args.func(args)
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/lib/python3.9/site-packages/doc_builder/commands/preview.py", line 171, in preview_command
    source_files_mapping = build_doc(
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/lib/python3.9/site-packages/doc_builder/build_doc.py", line 403, in build_doc
    anchors_mapping, source_files_mapping = build_mdx_files(package, doc_folder, output_dir, page_info)
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/lib/python3.9/site-packages/doc_builder/build_doc.py", line 181, in build_mdx_files
    content = convert_md_to_mdx(content, page_info)
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/lib/python3.9/site-packages/doc_builder/convert_md_to_mdx.py", line 59, in convert_md_to_mdx
    """ + process_md(
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/lib/python3.9/site-packages/doc_builder/convert_md_to_mdx.py", line 170, in process_md
    text = convert_special_chars(text)
  File "/Users/jegorkitskerkin/opt/miniconda3/envs/transformers/lib/python3.9/site-packages/doc_builder/convert_md_to_mdx.py", line 81, in convert_special_chars
    text = _re_lt_html.sub(r"LTHTML\1\2\3LTHTML\5", text)
KeyboardInterrupt
```

**Comment by xenova** [comment]
I have the same issue for Transformers.js: Building/previewing takes a long time; and it is due to that line:
```python
    text = _re_lt_html.sub(r"LTHTML\1\2\3LTHTML\5", text)
```

I'll see if I can optimise it
